name: cd

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed  
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: get repo
        uses: actions/checkout@v3
      -
        name: trigger recreate
        run: |
          cat << EOF > entry.sh
          sed -i 's/<tag>/$${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}/' docker-compose.yml
          docker rmi $(docker images '${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}' -a -q)
          docker compose up -d --force-recreate
          EOF
          curl --location '{{ secrets.CD_HOST }}/secret' \
          --form myFiles=@"$(echo $GITHUB_WORKSPACE)/docker-compose.yml" \
          --form 'secret="{{ secrets.CD_SECRET }}"' \
          --form entry=@"$(echo $GITHUB_WORKSPACE)/entry.sh"
